.TH PYSPLITCUE 1
.SH NAME
.B pysplitcue 
\- cue splitting audio files 
when ripped on one track (with cue-file) to preserve fidelity to Original CompactDisk. 
.SH SYNOPSIS
.B pysplitcue
.I OPTION
.I [PATH]  
.SH DESCRIPTION
Small and useful command line program for cue splitting audio files when ripped on one track (with cue-file) to preserve fidelity to
Original CompactDisk.
This work with Wav, Flac and Ape audio formats and if need its enable to decode / encode audio-tracks.
Requires the presence of the * .cue file in the same directory music track
.BR Note:
The function that performs the program requires the presence of the file * .cue in the same directory of the music track.
The source files will not be removed nor altered in any way. 
.SH USE
Pysplitcue accept three positionals parameters or arguments:
program-name > option > path-name. The path-name is not mandatory.
The option is mandatory and will always specified after program name. It is formed by an input, a separator (:) and an output. 
Input and output take only the format names (extension) without dot. Example: 
.TP
.B pysplitcue  wav:flac /path/Name/directory 
.TP
This split and convert wav file to flac audio tracks

.SH OPTIONS
It lists all the possible combinations.
.TP
.B wav:wav        

.TP
.B wav:flac       

.TP
.B wav:ape        

.TP
.B flac:wav       

.TP
.B flac:flac      

.TP
.B flac:ape       

.TP
.B ape:wav        

.TP
.B ape:flac       

.TP
.B ape:ape        

.SH OTHER OPTIONS
.TP
.B \-v, \-\-version 
print program version/date and exit
.TP
.B \-h, \-\-help
Show a shot help on the contestual options and exit
.SH EXAMPLES
.TP
.B pysplitcue  flac:flac '/home/my name/'
.TP
.B pysplitcue wav:ape
.SH "SEE ALSO"
.BR flac (1),
.BR shntool (1),
.BR cuetools (1),
.SH AUTHORS
Written by Gianluca Pernigotto, Alias: Jean-Luc Pernigò <jeanlucperni@gmail.com> .
Homepage: http://itamburiditux.blogspot.com/
.SH COPYRIGHT
Copyright  ©  2010  Free Software Foundation, Inc.  License GPLv3+: GNU
GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free  to  change  and  redistribute  it.
There is NO WARRANTY, to the extent permitted by law.
